SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

BEGIN
   DBMS_OUTPUT.put_line ('File PPM_MODULE_STATISTICS.sql started at ' || TO_CHAR (CURRENT_DATE, 'MON-DD-YYYY HH24:MI:SS') );
   
   ppm_db_utils.create_table('PPM_MODULE_STATISTICS','CREATE TABLE PPM_MODULE_STATISTICS(IP_ADDRESS  VARCHAR2(20 char),
	  DM NUMBER(5),
	  PM NUMBER(5),
	  PGM NUMBER(5),
	  TM NUMBER(5),
	  PFM NUMBER(5),
	  RM NUMBER(5),
	  FM NUMBER(5),
	  DASHBOARD NUMBER(5),
	  OTHERS NUMBER(5),
	  ACCESS_DATE DATE,
	 SERVER_NODE VARCHAR2(30 char))');
  
  ppm_db_utils.create_index('PPM_MODULE_STATISTICS_N1', 'CREATE UNIQUE INDEX PPM_MODULE_STATISTICS_N1 ON PPM_MODULE_STATISTICS(IP_ADDRESS, ACCESS_DATE, SERVER_NODE)');
             
   DBMS_OUTPUT.put_line ('File PPM_MODULE_STATISTICS.sql completed at ' || TO_CHAR (CURRENT_DATE, 'MON-DD-YYYY HH24:MI:SS') );
END;
/