SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

BEGIN
   DBMS_OUTPUT.put_line ('File PM_BASELINES_APPROVE_STATUS.sql started at ' || TO_CHAR (CURRENT_DATE, 'MON-DD-YYYY HH24:MI:SS') );
   
   ppm_db_utils.create_table('PM_BASELINES_APPROVE_STATUS','CREATE TABLE PM_BASELINES_APPROVE_STATUS(BASELINE_ID  NUMBER(19),
  APPROVED CHAR(1),
  REQUEST_ID NUMBER(19),
  UNIQUE(BASELINE_ID),
  UNIQUE(REQUEST_ID))');
             
   DBMS_OUTPUT.put_line ('File PM_BASELINES_APPROVE_STATUS.sql completed at ' || TO_CHAR (CURRENT_DATE, 'MON-DD-YYYY HH24:MI:SS') );
END;
/